name: admin
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.2.1+11

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: 5.5.1
  cloud_firestore: ^5.6.5
  cloud_functions: ^5.3.4
  firebase_storage: ^12.4.4
  
  # JS interop
  js: ^0.7.0
  
  # Outras dependências
  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.8
  flutter_html: ^3.0.0-beta.2
  http: ^1.2.2
  intl: ^0.20.2
  line_icons: ^2.0.3
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.8
  html_unescape: ^2.0.0
  googleapis_auth: ^1.6.0
  change_app_package_name: ^1.4.0
  flutter_dotenv: ^5.0.2
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Light.ttf
          weight: 400
        - asset: assets/fonts/Muli-Regular.ttf
          weight: 500
        - asset: assets/fonts/Muli-Medium.ttf
          weight: 600
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 800

  assets:
    - assets/images/icon.png
    - assets/.env
    - assets/fonts/
